version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s %(name)s [%(filename)s:%(lineno)d] [%(levelname)s] %(message)s"
    console:
        format: "\x1B[1;32m%(asctime)s [%(levelname)s] %(message)s\x1B[0m"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: console
        stream: ext://sys.stderr

    file_handler:
        class: logging.FileHandler
        level: DEBUG
        formatter: simple
        filename: log.txt
        encoding: utf8

root:
    level: DEBUG
    handlers: [console, file_handler]

## To use this logging config:
#G_DEFAULT_LOGGING_CONFIG = 'config/logging.yaml'
#if os.path.isfile(G_DEFAULT_LOGGING_CONFIG):
#    import yaml
#    with open(G_DEFAULT_LOGGING_CONFIG, 'r', encoding='utf8') as f:
#        logging.config.dictConfig(yaml.safe_load(f))
