resampler:
    sample_rate: 16000

fbank_feature_extractor:
    dither: 0.0
    num_mel_bins: 80

tokenizer: 
    vocab_path: model/tokenizer/AISHELL-1.vocab
    model_path: model/tokenizer/AISHELL-1.model

# under ops/core/
model_name: wenet
model_hparam: wenet.yaml

test_set:
    subsets:
    -   id: AISHELL-1-TEST
        max_num_samples: -1
