logging: config/logging.yaml
data_zoo: data/audio/zoo.yaml

test_set:
    subsets:
    -   id: AISHELL-1-TEST
        max_num_samples: -1

Resampler:
    sample_rate: 16000

FbankFeatureExtractor:
    dither: 0.0
    num_mel_bins: 80

Tokenizer: 
    vocab_path: model/tokenizer/AISHELL-1.vocab
    model_path: model/tokenizer/AISHELL-1.model

model: conformer
