logging: config/logging.yaml


dataset:
    train:
        subsets:
        -
            id: MINI
            root: dataset/MINI
            metadata: dataset/MINI/metadata.tsv
            max_num_samples: 0
        -
            id: GIGASPEECH_XS
            root: dataset/GIGASPEECH_XS
            metadata: dataset/GIGASPEECH_XS/metadata.tsv
            max_num_samples: -1
        -
            id: AISHELL-1-TRAIN
            root: /data/disk001/AISHELL-1/train
            metadata: /data/disk001/AISHELL-1/train/metadata.tsv
            max_num_samples: 0
        -
            id: AISHELL-2-IOS-TRAIN
            root: /data/disk001/AISHELL-2/iOS/train
            metadata: /data/disk001/AISHELL-2/iOS/train/metadata.tsv
            max_num_samples: 0

    valid:
        subsets:
        -
            id: MINI
            root: dataset/MINI
            metadata: dataset/MINI/metadata.tsv
            max_num_samples: 0
        -
            id: GIGASPEECH_DEV
            root: dataset/GIGASPEECH_DEV
            metadata: dataset/GIGASPEECH_DEV/metadata.tsv
            max_num_samples: 1
        -
            id: AISHELL-1-DEV
            root: /data/disk001/AISHELL-1/dev
            metadata: /data/disk001/AISHELL-1/dev/metadata.tsv
            max_num_samples: 0
        -
            id: AISHELL-2-IOS-DEV
            root: /data/disk001/AISHELL-2/iOS/dev
            metadata: /data/disk001/AISHELL-2/iOS/dev/metadata.tsv
            max_num_samples: 0

    test:
        subsets:
            -
                id: GIGASPEECH_TEST
                root: dataset/GIGASPEECH_TEST
                metadata: dataset/GIGASPEECH_TEST/metadata.tsv
                max_num_samples: 1
            -
                id: LIBRISPEECH_TEST_CLEAN
                root: /home/dophist/work/git/leaderboard/datasets/LIBRISPEECH_TEST_CLEAN
                metadata: /home/dophist/work/git/leaderboard/datasets/LIBRISPEECH_TEST_CLEAN/metadata.tsv
                max_num_samples: 0
            -
                id: LIBRISPEECH_TEST_OTHER
                root: /home/dophist/work/git/leaderboard/datasets/LIBRISPEECH_TEST_OTHER
                metadata: /home/dophist/work/git/leaderboard/datasets/LIBRISPEECH_TEST_OTHER/metadata.tsv
                max_num_samples: 0
            -
                id: AISHELL-1-TEST
                root: /data/disk001/AISHELL-1/test
                metadata: /data/disk001/AISHELL-1/test/metadata.tsv
                max_num_samples: 0
            -
                id: AISHELL-2-IOS-TEST
                root: /data/disk001/AISHELL-2/iOS/test
                metadata: /data/disk001/AISHELL-2/iOS/test/metadata.tsv
                max_num_samples: 0
            -
                id: SPEECHIO_ASR_ZH00000
                root: dataset/SPEECHIO_ASR_ZH00000
                metadata: dataset/SPEECHIO_ASR_ZH00000/metadata.tsv
                max_num_samples: 0

sample_loader:
    field_map:
        id: ID
        audio: AUDIO
        begin: BEGIN
        duration: DURATION
        text: TEXT
        speaker: SPEAKER

    min_duration: 0.5
    max_duration: 20.0
    

tokenizer:
    model: model/tokenizer/sentencepiece_en.model
    vocab: model/tokenizer/sentencepiece_en.vocab


dataloader:
    shuffle: True
    batch_size: 1
    drop_last: False
    num_workers: 4


feature:
    num_mel_bins: 80
    dither: 0.0
    mvn_shift: ''
    mvn_scale: ''


training:
    num_epochs: 20
    log_interval: 1000
    optimizer:
        Adam:
            lr: 0.001
        SGD:
            lr: 0.001
    scheduler:
        gamma: 0.95


model_sample_rate: 16000

model:
    idim: 80
    hidden_layer_dim: 2048
    odim: 256
