logging: config/logging.yaml


dataset:
    train:
        subsets:
            -
                id: SPEECHIO_ASR_ZH00000
                root: dataset/SPEECHIO_ASR_ZH00000
                metadata: dataset/SPEECHIO_ASR_ZH00000/metadata.tsv
                max_num_samples: 0
            -
                id: MINI
                root: dataset/MINI
                metadata: dataset/MINI/metadata.tsv
                max_num_samples: 0
            -
                id: AISHELL-1-TRAIN
                root: /data/disk001/AISHELL-1/train
                metadata: /data/disk001/AISHELL-1/train/metadata.tsv
                max_num_samples: 1e10
    valid:
        subsets:
            -
                id: AISHELL-1-DEV
                root: /data/disk001/AISHELL-1/dev
                metadata: /data/disk001/AISHELL-1/dev/metadata.tsv
                max_num_samples: 1000
    test:
        subsets:
            -
                id: AISHELL-1-TEST
                root: /data/disk001/AISHELL-1/test
                metadata: /data/disk001/AISHELL-1/test/metadata.tsv
                max_num_samples: 100


sample_loader:
    field_map:
        id: ID
        audio: AUDIO
        begin: BEGIN
        duration: DURATION
        text: TEXT
        speaker: SPEAKER

    min_duration: 0.5
    max_duration: 20.0
    

tokenizer:
    model: model/tokenizer/sentencepiece.model
    vocab: model/tokenizer/sentencepiece.vocab


dataloader:
    shuffle: True
    batch_size: 16
    drop_last: False
    num_workers: 4


feature:
    num_mel_bins: 80
    dither: 1.0


training:
    num_epochs: 2
    optimizer:
        Adam:
            lr: 0.001
    gradient_clipping:


model_sample_rate: 16000

model:
    idim: 80
    hidden_layer_dim: 128
    odim: 4096
