SampleLoader:
    field_map:
        id: ID
        audio: AUDIO
        begin: BEGIN
        duration: DURATION
        text: TEXT
        speaker: SPEAKER
    min_duration: 0.5
    max_duration: 20.0
    min_text_length: 1
    max_text_length: 1024

Resampler:
    sample_rate: 16000

Perturbation:
    mark_key: True
    speeds: #[0.9, 1.0, 1.1]
    tempos: #[0.9, 1.0, 1.1]
    volumes: #[0.9, 1.0, 1.1]

FbankFeatureExtractor:
    dither: 0.0
    num_mel_bins: 80

SpecAugment:
    mark_key: True
    num_t_masks: 2
    t_mask_width_max: 50
    num_f_masks: 2
    f_mask_width_max: 10

TextNormalizer:
    case: upper # either 'upper' or 'lower'

Tokenizer: 
    vocab_path: model/tokenizer/AISHELL-1.vocab
    model_path: model/tokenizer/AISHELL-1.model
    blk: '<blk>'
    bos: '<s>'
    eos: '</s>'
    unk: '<unk>'
    sil: '<sil>'

DataLoader:
    num_workers: 8
    shuffle: True
    drop_last: False
    batch_size: 8

# training
train_set:
    subsets:
    -   id: AISHELL-1-TRAIN
        max_num_samples: -1
valid_set:
    subsets:
    -   id: AISHELL-1-DEV
        max_num_samples: 20

model: conformer

num_epochs: 30
gradient_accumulation: 2
gradient_clipping: 5.0
log_interval: 100
optimizer:
    Adam:
        lr: 0.001
scheduler:
    warmup_steps: 25000
