logging: config/logging.yaml

data_zoo: data/audio/zoo.yaml

sample_rate: 16000

sample_loader:
    field_map:
        id: ID
        audio: AUDIO
        begin: BEGIN
        duration: DURATION
        text: TEXT
        speaker: SPEAKER
    min_duration: 0.5
    max_duration: 20.0
    min_text_length: 1
    max_text_length: 1024

dataset:
    train:
        subsets:
        -   id: GIGASPEECH_XS
            max_num_samples: 10
        -   id: GIGASPEECH_S
            max_num_samples: 0

    valid:
        subsets:
        -   id: GIGASPEECH_DEV
            max_num_samples: 1

    test:
        subsets:
        -   id: GIGASPEECH_TEST
            max_num_samples: 0
        -   id: LIBRISPEECH_TEST_CLEAN
            max_num_samples: 0
        -   id: LIBRISPEECH_TEST_OTHER
            max_num_samples: 0
    
tokenizer:
    model: model/tokenizer/sentencepiece_en.model
    vocab: model/tokenizer/sentencepiece_en.vocab

text_normalizer:
    case: UPPER # either 'UPPER' or 'lower'

dataloader:
    shuffle: True
    batch_size: 1
    drop_last: False
    num_workers: 4

augmentation:
    mark_key: True
    speeds: [0.9, 1.0, 1.1]
    tempos: #[0.9, 1.0, 1.1]
    rel_volumes: #[0.9, 1.0, 1.1]
    abs_volumes:

feature:
    num_mel_bins: 80
    dither: 0.0
    mvn_shift: ''
    mvn_scale: ''

training:
    num_epochs: 2
    log_interval: 10
    optimizer:
        Adam:
            lr: 0.001
        SGD:
            lr: 0.001
    scheduler:
        gamma: 0.5

model:
    idim: 80
    hidden_layer_dim: 256
    num_hidden_layers: 3
    odim: 32
