sentencepiece:
    # https://github.com/google/sentencepiece/blob/master/doc/options.md
    model_type: unigram # ["unigram", "bpe", "char"]
    vocab_size: 1024
    character_coverage: 1.0
    user_defined_symbols: "" # comma seperated symbols
    pad_id: 0
    bos_id: 
    eos_id: 2
    unk_id: 3
    pad_piece: <blk> # blank
    bos_piece: <s>
    eos_piece: </s>
    unk_piece: <unk> 
    max_sentencepiece_length: 16 # default 16
    add_dummy_prefix: true
    num_threads: 40
    train_extremely_large_corpus: true
